### PR TITLE
Added the missing "return" keyword

### PR DESCRIPTION
**Pull request by JasonHK**

### CODE REVIEW

**Comment by AlexandreCantin** [comment]
Thanks @JasonHK 

For your information, I don't spend time working on this project anymore... :disappointed: 
So using `react-forms-helper` is at your risk...

**Comment by JasonHK** [comment]
If you don't mind, can I become the maintainer of the package?

**Comment by AlexandreCantin** [comment]
Sure, no problem !
I have added you as contributor but I will directly transfer you the ownership of the project !

**Comment by AlexandreCantin** [comment]
I've got this error while transferring the repo ownership `JasonHK/preact-forms-helper already exists`.

Can you delete delete your repo @JasonHK and notify when it's done ?
By the way, do you have a NPM account ?

Thank you :smile:

**Comment by JasonHK** [comment]
Okay, I've deleted the repo. Also, this is my npm account: https://www.npmjs.com/~jasonhk

**Comment by JasonHK** [comment]
@AlexandreCantin Could you try to transfer again? It should work this time.

**Pull request merged**
